exampleURL/urls.py
from django.urls import path, re_path, register_converter, include

from . import views, converters

register_converter(converters.FourDigitYearConverter, 'yyyy')
register_converter(converters.TwoDigitMonthConverter, 'mm')

app_name = 'exampleURL'
urlpatterns = [
    path('', views.index, name='index'),
    path('articles/2009/', views.special_case_2009, name='special_case_2009'),
    path('articles/<int:year>/', views.year_archive, name='year_archive'),
    path('articles/<int:year>/<int:month>/', views.month_archive,
         name='month_archive'),
    path('articles/<int:year>/<int:month>/<slug:slug>/', views.article_detail,
         name='article_detail'),

    # use convertor
    path('articles/<yyyy:year>/<mm:month>/<slug:slug>/',
         views.article_detail_converters,
         name='article_detail_converters'),

    # use regexp
    re_path(
        r'^articles/(?P<year>[12][0-9]{3})/(?P<month>0[1-9]|1[0-2])/(?P<slug>[\w-]+)/$',
        views.article_detail_regexp, name='article_detail_regexp'),

    # задание аргументов по умолчанию (views)
    path('blog/', include([
        path('', views.page, name='page1'),
        path('page<int:num>/', views.page, name='page2'),
    ])),

    # передача дополнительных параметров
    path('parameter_passing/', views.parameter_passing, {'param1': 73, 'param2': 37}, name='parameter_passing'),
]

handling_HTTP_requests/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exampleURL.urls')),
    path('exampleURL/', include('exampleURL.urls')),
]

exampleURL/models.py
from django.db import models

# Create your models here.

exampleURL/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'exampleURL/index.html', locals())


def special_case_2009(request):
    return render(request, 'exampleURL/special_case_2009.html', locals())


def year_archive(request, year):
    return render(request, 'exampleURL/year_archive.html', locals())


def month_archive(request, year, month):
    return render(request, 'exampleURL/month_archive.html', locals())


def article_detail(request, year, month, slug):
    return render(request, 'exampleURL/article_detail.html', locals())


def article_detail_converters(request, year, month, slug):
    return render(request, 'exampleURL/article_detail_converters.html', locals())


def article_detail_regexp(request, year, month, slug):
    return render(request, 'exampleURL/article_detail_regexp.html', locals())


def page(request, num=73):
    return render(request, 'exampleURL/page.html', locals())


def parameter_passing(request, param1, param2):
    return render(request, 'exampleURL/parameter_passing.html', locals())

templates/exampleURL/article_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Views: article_detail</h1>
    <h3>year: {{ year }}</h3>
    <h3>month: {{ month }}</h3>
    <h3>slug: {{ slug }}</h3>
    <a href="{% url 'exampleURL:index' %}">Back</a>
</body>
</html>

templates/exampleURL/article_detail_converters.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Views: article_detail_converters</h1>
    <h3>year: {{ year }}</h3>
    <h3>month: {{ month }}</h3>
    <h3>slug: {{ slug }}</h3>
    <a href="{% url 'exampleURL:index' %}">Back</a>
</body>
</html>

templates/exampleURL/article_detail_regexp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Views: article_detail_regexp</h1>
    <h3>year: {{ year }}</h3>
    <h3>month: {{ month }}</h3>
    <h3>slug: {{ slug }}</h3>
    <a href="{% url 'exampleURL:index' %}">Back</a>
</body>
</html>

templates/exampleURL/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{% url 'exampleURL:special_case_2009' %}">exampleURL:special_case_2009</a><br>
    <a href="{% url 'exampleURL:year_archive' 12 %}">exampleURL:year_archive</a> with year: 12<br>
    <a href="{% url 'exampleURL:year_archive' 14 %}">exampleURL:year_archive</a> with year: 14<br>
    <a href="{% url 'exampleURL:year_archive' 18 %}">exampleURL:year_archive</a> with year: 18<br>
    <a href="{% url 'exampleURL:month_archive' 18 222 %}">exampleURL:month_archive</a> with year: 18 and month: 222<br>
    <a href="{% url 'exampleURL:month_archive' 19 224 %}">exampleURL:month_archive</a> with year: 19 and month: 224<br>
    <a href="{% url 'exampleURL:month_archive' 20 226 %}">exampleURL:month_archive</a> with year: 20 and month: 226<br>
    <a href="{% url 'exampleURL:article_detail' 20 229 'qwerty' %}">exampleURL:article_detail</a> with year: 20, month: 229 and slug: 'qwerty'<br>
    <a href="{% url 'exampleURL:article_detail' 22 212 'asdfgh' %}">exampleURL:article_detail</a> with year: 22, month: 212 and slug: 'asdfgh'<br>
    <a href="{% url 'exampleURL:article_detail' 24 211 'zxcvbn' %}">exampleURL:article_detail</a> with year: 24, month: 211 and slug: 'zxcvbn'<br>
    <a href="{% url 'exampleURL:article_detail_converters' 1998 09 'qwerty' %}">exampleURL:article_detail_converters</a> with year: 1998, month: 09 and slug: 'qwerty'<br>
    <a href="{% url 'exampleURL:article_detail_converters' 2009 01 'qwerty' %}">exampleURL:article_detail_converters</a> with year: 2009, month: 01 and slug: 'qwerty'<br>
    <a href="{% url 'exampleURL:article_detail_converters' 2015 11 'qwerty' %}">exampleURL:article_detail_converters</a> with year: 2015, month: 01 and slug: 'qwerty'<br>
    <a href="{% url 'exampleURL:article_detail_regexp' '1998' '09' 'qwerty' %}">exampleURL:article_detail_regexp</a> with year: 1998, month: 09 and slug: 'qwerty'<br>
    <a href="{% url 'exampleURL:article_detail_regexp' '2009' '01' 'qwerty' %}">exampleURL:article_detail_regexp</a> with year: 2009, month: 01 and slug: 'qwerty'<br>
    <a href="{% url 'exampleURL:article_detail_regexp' '2015' '11' 'qwerty' %}">exampleURL:article_detail_regexp</a> with year: 2015, month: 01 and slug: 'qwerty'<br>
    <a href="{% url 'exampleURL:page2' 77 %}">exampleURL:page</a> with num: 77<br>
    <a href="{% url 'exampleURL:page1' %}">exampleURL:page</a> without num<br>
    <a href="{% url 'exampleURL:parameter_passing' %}">exampleURL:parameter_passing</a> without parameters<br>
</body>
</html>

templates/exampleURL/month_archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Views: month_archive</h1>
    <h3>year: {{ year }}</h3>
    <h3>month: {{ month }}</h3>
    <a href="{% url 'exampleURL:index' %}">Back</a>
</body>
</html>

templates/exampleURL/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Views: page</h1>
    <h3>num: {{ num }}</h3>
    <a href="{% url 'exampleURL:index' %}">Back</a>
</body>
</html>

templates/exampleURL/parameter_passing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Views: parameter passing</h1>
    <h3>param1: {{ param1 }}</h3>
    <h3>param2: {{ param2 }}</h3>
    <a href="{% url 'exampleURL:index' %}">Back</a>
</body>
</html>

templates/exampleURL/special_case_2009.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Views: special_case_2009</h1>
    <a href="{% url 'exampleURL:index' %}">Back</a>
</body>
</html>

templates/exampleURL/year_archive.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Views: year_archive</h1>
    <h3>year: {{ year }}</h3>
    <a href="{% url 'exampleURL:index' %}">Back</a>
</body>
</html>